#!/usr/bin/env bash
# E16 — Stand up the gateway + local LLM against a pre-existing Wazuh.
#
# Orchestrates: keys, securityconfig, environments.yaml, manager executors,
# compose/systemd for tool-service + auth-shim (+ optional Ollama).
# Never runs `make wazuh`.
#
# Usage:
#   cp deploy.env.example deploy.env   # fill endpoints + creds
#   bash scripts/install_gateway.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck disable=SC1091
source "$ROOT/scripts/lib/deploy_common.sh"

deploy_load_env "$ROOT"
cd "$ROOT"

DEPLOY_MODE="${DEPLOY_MODE:-compose}"
COMPOSE_FILE="${COMPOSE_FILE:-docker-compose.poc.yml}"
COMPOSE_NETWORK="${COMPOSE_NETWORK:-single-node_default}"
SECURITYCONFIG_MODE="${SECURITYCONFIG_MODE:-docker}"
ENVIRONMENTS_OUT="${ENVIRONMENTS_OUT:-environments.yaml}"
ACTIONS_TIERS="${ACTIONS_TIERS:-dashboard}"
SETUP_MANAGER_EXECUTORS="${SETUP_MANAGER_EXECUTORS:-auto}"
START_OLLAMA="${START_OLLAMA:-true}"
PULL_OLLAMA_MODEL="${PULL_OLLAMA_MODEL:-true}"
OLLAMA_MODEL="${OLLAMA_MODEL:-gpt-oss:20b}"
WAI_ENV_ID="${WAI_ENV_ID:-lab}"

ensure_keys() {
  deploy_log "Ensuring JWT keypair (keys/gen-keys.sh — idempotent)"
  chmod +x "$ROOT/keys/gen-keys.sh"
  "$ROOT/keys/gen-keys.sh" "$ROOT/keys"
  [[ -f "$ROOT/keys/jwt-public.pem" ]] || deploy_fail "jwt-public.pem missing after keygen"
}

ensure_gateway_key() {
  if [[ -z "${WAI_ENV_LAB_KEY:-}" ]]; then
    WAI_ENV_LAB_KEY="$(openssl rand -hex 32)"
    export WAI_ENV_LAB_KEY
    deploy_warn "Generated WAI_ENV_LAB_KEY=$WAI_ENV_LAB_KEY — persist it in deploy.env"
  fi
}

apply_securityconfig() {
  case "$SECURITYCONFIG_MODE" in
    docker)
      deploy_require INDEXER_CONTAINER
      if ! docker ps --format '{{.Names}}' | grep -qx "$INDEXER_CONTAINER"; then
        deploy_fail "INDEXER_CONTAINER=$INDEXER_CONTAINER is not running.
Set SECURITYCONFIG_MODE=merge-only for a package-installed indexer, or fix the container name."
      fi
      export CONTAINER="$INDEXER_CONTAINER"
      export INDEXER_URL INDEXER_ADMIN_USER INDEXER_ADMIN_PASSWORD
      deploy_log "Applying securityconfig via securityconfig/apply.sh (container=$INDEXER_CONTAINER)"
      chmod +x "$ROOT/securityconfig/apply.sh"
      (cd "$ROOT/securityconfig" && ./apply.sh)
      ;;
    merge-only)
      local work="${INDEXER_SC_WORKDIR:-/tmp/wazuh-ai-securityconfig}"
      mkdir -p "$work"
      local missing=0 f
      for f in config.yml roles.yml roles_mapping.yml internal_users.yml; do
        if [[ ! -f "$work/$f" ]]; then
          deploy_warn "missing $work/$f"
          missing=1
        fi
      done
      if [[ "$missing" -eq 1 ]]; then
        deploy_fail "SECURITYCONFIG_MODE=merge-only requires live copies of
config.yml roles.yml roles_mapping.yml internal_users.yml in $work
(copy them from your indexer securityconfig dir, then re-run).
After a successful merge, apply with your indexer's securityadmin.sh (pin the env CA)."
      fi
      deploy_log "Merging wazuh-ai JWT domain + roles into $work"
      python3 "$ROOT/securityconfig/merge_securityconfig.py" "$work" "$ROOT/keys/jwt-public.pem"
      deploy_log "Merged. Apply with securityadmin.sh against these files, then restart/reload as you normally would."
      echo "  Example (paths vary by install):"
      echo "    securityadmin.sh -f $work/config.yml -t config -icl -nhnv \\"
      echo "      -cacert <root-ca.pem> -cert <admin.pem> -key <admin-key.pem> -h <indexer-host>"
      ;;
    *)
      deploy_fail "Unknown SECURITYCONFIG_MODE=$SECURITYCONFIG_MODE (docker|merge-only)"
      ;;
  esac
}

write_environments_yaml() {
  local out="$ROOT/$ENVIRONMENTS_OUT"
  local example="$ROOT/environments.yaml.example"
  [[ -f "$example" ]] || deploy_fail "missing $example"
  ensure_gateway_key

  # Build actions YAML list from ACTIONS_TIERS
  local tiers_yaml="" t
  IFS=',' read -ra _tiers <<< "$ACTIONS_TIERS"
  for t in "${_tiers[@]}"; do
    t="${t#"${t%%[![:space:]]*}"}"
    t="${t%"${t##*[![:space:]]}"}"
    [[ -n "$t" ]] || continue
    tiers_yaml+="    - $t"$'\n'
  done
  [[ -n "$tiers_yaml" ]] || tiers_yaml="    - dashboard"$'\n'

  deploy_log "Writing $out from template + deploy.env"
  cat > "$out" <<EOF
# Generated by scripts/install_gateway.sh — review before production use.
- env_id: ${WAI_ENV_ID}
  gateway_key: ${WAI_ENV_LAB_KEY}
  indexer_url: ${INDEXER_URL}
  indexer_ca_path: "${INDEXER_CA_PATH:-}"
  reader_basic: ${WAI_ENV_LAB_READER:-wazuh_ai_env_reader:EnvReaderLab1!}
  embed_ml_model_id: ${WAI_EMBED_ML_MODEL_ID:-}
  locale: bilingual
  actions:
${tiers_yaml}  dashboard_api_url: ${WAI_ENV_LAB_DASHBOARD_API_URL:-}
  dashboard_executor_basic: ${WAI_ENV_LAB_DASHBOARD_EXECUTOR:-}
  monitor_executor_basic: ${WAI_ENV_LAB_MONITOR_EXECUTOR:-}
  manager_api_url: ${MANAGER_API_URL:-}
  manager_ca_path: "${MANAGER_CA_PATH:-}"
  manager_executor_basic: ${WAI_ENV_LAB_MANAGER_EXECUTOR:-}
  ar_executor_basic: ${WAI_ENV_LAB_AR_EXECUTOR:-}
  manager_actions_per_hour: 10
  active_response_actions_per_hour: 5
EOF
  deploy_log "Wrote $out"
}

maybe_manager_executors() {
  local need=false
  [[ "$ACTIONS_TIERS" == *manager* || "$ACTIONS_TIERS" == *active_response* ]] && need=true
  if [[ "$SETUP_MANAGER_EXECUTORS" == "false" ]]; then
    return 0
  fi
  if [[ "$SETUP_MANAGER_EXECUTORS" == "auto" && "$need" != "true" ]]; then
    deploy_log "No manager/active_response tiers — skipping manager_executor_setup.sh"
    return 0
  fi
  if [[ "${WAZUH_ADMIN:-}" == *CHANGE_ME* || -z "${WAZUH_ADMIN:-}" ]]; then
    deploy_warn "WAZUH_ADMIN not set — skip executor RBAC; run scripts/manager_executor_setup.sh later"
    return 0
  fi
  deploy_log "Creating least-privilege manager/AR users via scripts/manager_executor_setup.sh"
  chmod +x "$ROOT/scripts/manager_executor_setup.sh"
  export WAZUH_API_URL WAZUH_ADMIN WAI_MANAGER_OP_PASSWORD WAI_AR_EXEC_PASSWORD
  "$ROOT/scripts/manager_executor_setup.sh"
}

ensure_compose_network() {
  if ! docker network inspect "$COMPOSE_NETWORK" >/dev/null 2>&1; then
    deploy_fail "Docker network '$COMPOSE_NETWORK' not found.
The gateway must join the same network as your Wazuh indexer so ML Commons can call tool-service.
Create/attach the network, or set COMPOSE_NETWORK to the name from: docker network ls"
  fi
  # Patch compose external network name if needed (operator may override via env only —
  # docker-compose.poc.yml hardcodes single-node_default; document override).
  if [[ "$COMPOSE_NETWORK" != "single-node_default" ]]; then
    deploy_warn "COMPOSE_NETWORK=$COMPOSE_NETWORK — ensure $COMPOSE_FILE 'networks.wazuh.name' matches, or use an override file."
  fi
}

start_compose() {
  deploy_command_exists docker || deploy_fail "docker required for DEPLOY_MODE=compose"
  ensure_compose_network
  [[ -f "$ROOT/$COMPOSE_FILE" ]] || deploy_fail "missing $ROOT/$COMPOSE_FILE"

  # Export knobs compose reads from the shell / .env
  export WAI_LLM_PROVIDER="${WAI_LLM_PROVIDER:-openai}"
  export WAI_LLM_BASE_URL="${WAI_LLM_BASE_URL:-http://ollama:11434/v1}"
  export WAI_MODEL_ROUTER="${WAI_MODEL_ROUTER:-$OLLAMA_MODEL}"
  export WAI_MODEL_ANALYSIS="${WAI_MODEL_ANALYSIS:-$OLLAMA_MODEL}"
  export WAI_ENV_LAB_KEY INDEXER_URL
  export WAI_INDEXER_URL="${WAI_INDEXER_URL:-$INDEXER_URL}"
  export WAI_ENVS_FILE="/config/environments.yaml"

  # Point compose at generated environments.yaml via a bind — use environments.poc.yaml
  # path only if ENVIRONMENTS_OUT is the default environments.yaml; copy for the volume.
  if [[ "$ENVIRONMENTS_OUT" != "environments.poc.yaml" ]]; then
    cp -f "$ROOT/$ENVIRONMENTS_OUT" "$ROOT/environments.poc.yaml"
    deploy_log "Synced $ENVIRONMENTS_OUT → environments.poc.yaml for compose volume"
  fi

  if [[ "$START_OLLAMA" == "true" && "${WAI_LLM_PROVIDER}" == "openai" ]]; then
    deploy_log "Starting Ollama profile"
    docker compose -f "$ROOT/$COMPOSE_FILE" --profile ollama up -d ollama
    if [[ "$PULL_OLLAMA_MODEL" == "true" ]]; then
      deploy_log "Pulling Ollama model $OLLAMA_MODEL (may take a while)"
      docker compose -f "$ROOT/$COMPOSE_FILE" --profile ollama exec -T ollama \
        ollama pull "$OLLAMA_MODEL" || deploy_warn "ollama pull failed — pull manually"
    fi
  fi

  deploy_log "Building and starting tool-service + auth-shim"
  docker compose -f "$ROOT/$COMPOSE_FILE" up -d --build auth-shim tool-service
}

install_systemd_units() {
  local dest="${SYSTEMD_INSTALL_DIR:-/opt/wazuh-ai}"
  local unit_dir="${SYSTEMD_UNIT_DIR:-/etc/systemd/system}"
  [[ "$(id -u)" -eq 0 ]] || deploy_fail "DEPLOY_MODE=systemd requires root"
  deploy_log "Installing compose project symlink at $dest and systemd units"
  mkdir -p "$dest"
  if [[ ! -e "$dest/docker-compose.poc.yml" ]]; then
    ln -sfn "$ROOT" "$dest/repo" 2>/dev/null || true
  fi
  install -m 644 "$ROOT/scripts/systemd/wazuh-ai-gateway.service" "$unit_dir/"
  # Rewrite WorkingDirectory to ROOT
  sed -i "s|/opt/wazuh-ai|$ROOT|g" "$unit_dir/wazuh-ai-gateway.service"
  systemctl daemon-reload
  systemctl enable --now wazuh-ai-gateway.service
  deploy_log "Enabled wazuh-ai-gateway.service (wraps docker compose for tool-service + auth-shim)"
}

wait_health() {
  local i
  for i in $(seq 1 30); do
    if curl -sf "http://127.0.0.1:${WAI_CONNECTOR_PORT:-8080}/healthz" >/dev/null 2>&1 \
      || curl -sf "http://127.0.0.1:${WAI_CONNECTOR_PORT:-8080}/v1/tools" >/dev/null 2>&1; then
      deploy_log "Gateway is up on :${WAI_CONNECTOR_PORT:-8080}"
      return 0
    fi
    sleep 2
  done
  deploy_warn "Gateway health check timed out — check: docker compose -f $COMPOSE_FILE logs tool-service"
  return 1
}

# ---- main -------------------------------------------------------------------
deploy_preflight_banner "install_gateway.sh (E16)"
echo " mode:       $DEPLOY_MODE"
echo " security:   $SECURITYCONFIG_MODE"
echo " actions:    $ACTIONS_TIERS"
echo " llm:        ${WAI_LLM_PROVIDER:-?} / ${WAI_MODEL_ANALYSIS:-?}"
echo

deploy_check_indexer
ensure_keys
apply_securityconfig
write_environments_yaml
maybe_manager_executors

case "$DEPLOY_MODE" in
  compose)
    start_compose
    ;;
  systemd)
    start_compose
    install_systemd_units
    ;;
  *)
    deploy_fail "Unknown DEPLOY_MODE=$DEPLOY_MODE (compose|systemd)"
    ;;
esac

wait_health || true

deploy_log "Done. Verification:"
echo "  1. curl -sf http://127.0.0.1:${WAI_CONNECTOR_PORT:-8080}/healthz  (or /v1/tools)"
echo "  2. From the indexer host, confirm reachability of"
echo "     http://${WAI_CONNECTOR_HOST:-tool-service}:${WAI_CONNECTOR_PORT:-8080}/v1/connector/analyze"
echo "  3. Run install_dashboard_assistant.sh (if not already) so ML Commons trusts that URL."
echo "  4. Ask a question in the Dashboard Assistant; check the verifiability label."
echo "  5. Optional: make evals-connector against this environment."
