{{- if and (eq .Values.certs.mode "helm") (or .Values.indexer.enabled .Values.manager.enabled .Values.dashboard.enabled) }}
{{- include "wazuh.certs" . }}
{{- $c := .Values._wazuhCerts }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wazuh.indexerCertsSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wazuh.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}{{- toYaml . | nindent 4 }}{{- end }}
type: Opaque
data:
  root-ca.pem: {{ index $c "root-ca.pem" | b64enc | quote }}
  node.pem: {{ index $c "node.pem" | b64enc | quote }}
  node-key.pem: {{ index $c "node-key.pem" | b64enc | quote }}
  admin.pem: {{ index $c "admin.pem" | b64enc | quote }}
  admin-key.pem: {{ index $c "admin-key.pem" | b64enc | quote }}
  filebeat.pem: {{ index $c "filebeat.pem" | b64enc | quote }}
  filebeat-key.pem: {{ index $c "filebeat-key.pem" | b64enc | quote }}
  dashboard.pem: {{ index $c "dashboard.pem" | b64enc | quote }}
  dashboard-key.pem: {{ index $c "dashboard-key.pem" | b64enc | quote }}
{{- if .Values.dashboard.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wazuh.dashboardCertsSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wazuh.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}{{- toYaml . | nindent 4 }}{{- end }}
type: Opaque
data:
  root-ca.pem: {{ index $c "root-ca.pem" | b64enc | quote }}
  cert.pem: {{ index $c "dashboard-http.pem" | b64enc | quote }}
  key.pem: {{ index $c "dashboard-http-key.pem" | b64enc | quote }}
{{- end }}
{{- end }}
