{{- if .Values.serviceAccount.create }}
{{- $components := list }}
{{- if .Values.manager.enabled }}{{- $components = append $components "manager" }}{{- end }}
{{- if .Values.indexer.enabled }}{{- $components = append $components "indexer" }}{{- end }}
{{- if .Values.dashboard.enabled }}{{- $components = append $components "dashboard" }}{{- end }}
{{- if .Values.agent.enabled }}{{- $components = append $components "agent" }}{{- end }}
{{- range $component := $components }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wazuh.component.serviceAccountName" (dict "context" $ "component" $component) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "wazuh.component.labels" (dict "context" $ "component" $component) | nindent 4 }}
    {{- with $.Values.commonLabels }}{{- toYaml . | nindent 4 }}{{- end }}
  {{- with (merge (dict) $.Values.serviceAccount.annotations $.Values.commonAnnotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
